### PR TITLE
Configuring for zope-product

### PR DESCRIPTION
**Pull request by gforcada**
Update the distribution's configuration.

@mauritsvanrees Plone 5.2 is using `master` branch of `five.customerize`, but Zope Foundation packages are no longer supporting (from its `meta` _configurator_) python 2.7/3.5/3.6.

Should we create a `2.1.x` branch and use that for Plone 5.2 release series, so we can make `master` python 3 only? 🤔 

#19 needs `tox`/GitHub Actions adjustments to get a green pipeline 🍏 😄 

🍀

### CODE REVIEW

**Comment by dataflake** [comment]
Creating a branch to keep backwards-compatibility for those who need it is the accepted solution in cases like this. But please don't make it a `2.1` branch, make it a `2.x`, otherwise you're saying that a release `2.2` is not from that branch.

**Comment by mauritsvanrees** [comment]
Indeed, I always go with 2.x in these cases.

**Comment by gforcada** [comment]
Indeed, sorry, [`2.x`](https://github.com/zopefoundation/five.customerize/tree/2.x) branch has been created and [`buildout.coredev`](https://github.com/plone/buildout.coredev/commit/d012578061542c97f5a1df88ea436a9e44cb945b) branch __5.2__ has been updated with it 🎉

**Comment by dataflake** [comment]
Please change `author_email` in `setup.py` to "zope-dev@zope.dev" - the zope.org domain is still not under Plone Foundation control.

**Comment by gforcada** [comment]
> Please change `author_email` in `setup.py` to "[zope-dev@zope.dev](mailto:zope-dev@zope.dev)" - the zope.org domain is still not under Plone Foundation control.

Done 👍🏾

**Review by icemac — APPROVED** [review]
LGTM

**Pull request merged**
