### PR TITLE
(WIP) Switch to plone.testing to avoid test isolation issues

### PR DESCRIPTION
**Pull request by davisagli**
Pushing this as a work in progress before I head to bed. The converted tests pass in isolation but I'm still getting an error when run as part of the full Plone tests...some problem while trying to create a local ZCA site manager using five.localsitemanager, related to the stacked component registries from plone.testing:

```
Error in test /Users/davisagli/.buildout/eggs/five.localsitemanager-3.1-py3.6.egg/five/localsitemanager/browser.txt
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/doctest.py", line 2282, in debug
    runner.run(self._dt_test, clear_globs=False)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/doctest.py", line 1839, in run
    r = DocTestRunner.run(self, test, compileflags, out, False)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/doctest.py", line 1476, in run
    return self.__run(test, compileflags, out)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/doctest.py", line 1382, in __run
    exception)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/doctest.py", line 1845, in report_unexpected_exception
    raise UnexpectedException(test, example, exc_info)
doctest.UnexpectedException: <DocTest browser.txt from /Users/davisagli/.buildout/eggs/five.localsitemanager-3.1-py3.6.egg/five/localsitemanager/browser.txt:0 (27 examples)>

IndexError: tuple index out of range

> /Users/davisagli/.buildout/eggs/five.localsitemanager-3.1-py3.6.egg/five/localsitemanager/browser.py(40)sitemanagerTrail()
-> sm = sm.__bases__[0]
(Pdb) l
 35     
 36             sm = self.context.getSiteManager()
 37             trail = []
 38             while sm is not None and sm != base:
 39                 trail.append(repr(sm))
 40  ->             sm = sm.__bases__[0]
 41     
 42             if sm == base:
 43                 trail.append('Global Registry')
 44     
 45             trail.reverse()
(Pdb) sm
<BaseGlobalComponents base>
(Pdb) sm.__bases__
()
(Pdb) base
<BaseGlobalComponents test-stack-2>
```

### CODE REVIEW

**Comment by ale-rt** [comment]
It looks to me like everything is fine.
Anyway I do not get which version/branch of plone.testing has plone.testing.zope instead of plone.testing.z2.
Test pass on Py2.7 in this branch https://github.com/zopefoundation/five.customerize/compare/plone-testing...plone-testing-ale?expand=1 but of course I do not want it merged because it pulls in the ZServer.

**Comment by ale-rt** [comment]
Stupid me... the test pass with the plone.testing branch py3_disallow_commits

**Comment by jensens** [comment]
`py3_disallow_commits` was merged to master

**Comment by jensens** [comment]
After a release of plone.testing TravisCI will be green here.

**Pull request merged**
