### PR TITLE
Clarify supported Zope versions + fix deprecation warnings.

### PR DESCRIPTION
**Pull request by icemac**

### CODE REVIEW

**Comment by davisagli** [comment]
FYI I am going to create a `1.x` branch at the point before this was merged, and update Plone 4.3 and 5.1 to use that branch.

**Comment by icemac** [comment]
@davisagli You are welcome.

**Comment by icemac** [comment]
@davisagli There is already https://github.com/zopefoundation/five.customerize/tree/1.x which might fit the needs.

**Comment by davisagli** [comment]
@icemac yes, I created that after my comment here. :)

**Pull request merged**
